#--------------------------通用配置-------------------------
spring:
  application:
    name: book_test_master
server:
  # 服务端口号
  port: 8080
# 开启 MyBatis Plus SQL 输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345


--- #---------------------自定义配置---------------------------
book:
  #跨域配置
  cors:
    #允许跨域的域名
    allow-origins:
      - http://localhost:5173
  # JWT密钥
  jwt:
    secret: E66559580A1ADF48CDD928516062F12E


